### ISSUE TITLE
unexplained drift / outward velocity

### ISSUE THREAD

**Issue by jaredmcqueen** [Brenden-Morales/ThreeForce#2]
Brenden,
I've been using your project as a framework for implementing fruchterman reingold in GLSL.  My issue is that I get a stable structure that randomly drifts around the screen.  There's got to be some weird velocities at play here but I can't figure it out.  

I wrote my own repulsion / attraction functions using the FR technique.  I get the random drift using my new functions, or your existing functions.

In order to debug, I wrote the whole thing in javascript, using three.js instead of the shaders for compute.  I get the exact outcome I expect.

http://jaredmcqueen.github.io/gpgpu-force-direction/canvas_app.html
http://jaredmcqueen.github.io/gpgpu-force-direction/gpgpu_app.html

What is causing this random drift?  The structure unfolds correctly, but then some outside forces start pushing it around the screen.  Comment out my functions, and uncomment your existing ones -- you'll see the same drift.

**Comment by jaredmcqueen** [comment]
also:
http://stackoverflow.com/questions/32999292/random-velocities-when-using-simulation-shader

**Comment by Brenden-Morales** [comment]
The first thing that comes to mind is to check if you're adding weight to the vertices and applying gravity. I don't have a lot of time to poke at it now but that's where I'd start.

**Comment by jaredmcqueen** [comment]
The nice thing about FR is that you don't need to push things towards the origin, so no gravity and no outside forces.

When it comes to edge evaluation using the x,y,z,w components - did you come up with that on your own or find some example to work off of?  I'm guessing there is unnecessary attraction causing the weirdness.

**Comment by jaredmcqueen** [comment]
edge iteration code was flawed, updated SO question.  closed.
